project 'Hack AZ.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hack AZ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hack AZ
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'Hack AZTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hack AZUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
